### PR TITLE
Prevent sending coins when there is less than one UTXO

### LINKED ISSUE #115: Prevent sending coins when there is less than one UTXO
Attempting to use the last `UTXO` results in an assertion error. There would be no `UTXO`s left if that one was used.
The faucet should check the number of `UTXO`s before sending and prevent sending if there is only one .
The log is very clear :

```
Jun 28 05:12:55 eu-001.bosagora.io docker[537610]: [main(gbGR) INF] About to send transactions...
Jun 28 05:12:55 eu-001.bosagora.io docker[537610]: [main(gbGR) INF]         UTXO set: 31 entries
Jun 28 05:12:55 eu-001.bosagora.io docker[537610]: [main(gbGR) INF]         Median: 180740740740740, Avg: 157419354838709
Jun 28 05:12:55 eu-001.bosagora.io docker[537610]: [main(gbGR) INF]         L: 2, H: 542222222222222
Jun 28 05:13:00 eu-001.bosagora.io docker[537610]: [main(yZVg) INF] Updating state: blocks [530 .. 530] (1)
Jun 28 05:13:00 eu-001.bosagora.io docker[537610]: [main(yZVg) INF] UTXO delta: -30
Jun 28 05:13:00 eu-001.bosagora.io docker[537610]: [main(yZVg) INF] About to send transactions...
Jun 28 05:13:00 eu-001.bosagora.io docker[537610]: [main(yZVg) INF]         UTXO set: 1 entries
Jun 28 05:13:00 eu-001.bosagora.io docker[537610]: [main(yZVg) INF]         Median: 4880000000000000, Avg: 4880000000000000
Jun 28 05:13:00 eu-001.bosagora.io docker[537610]: [main(yZVg) INF]         L: 4880000000000000, H: 4880000000000000
Jun 28 05:13:00 eu-001.bosagora.io docker[537610]: [main(EE3r) INF] Sending 100 BOA to boa1xpy00m8r9qpmkh8zznkn3jc9w9n3t6x3wdzx4sdsd9xqjk3m0dwzx9ecvul
Jun 28 05:13:02 eu-001.bosagora.io docker[537610]: core.exception.AssertError@/usr/include/d/std/algorithm/iteration.d(1408): Attempting to fetch the front of an empty filter.
```

### PR DESCRIPTION
**Pull request by kchulj**
Attempting to send coins without any `UTXO` or with one `UTXO` results in an assertion error.
The faucet now checks the number of `UTXO`s before sending and prevents sending if there is less than one.

Fixes #115

### CODE REVIEW

**Comment by kchulj** [comment]
Depends on #117.
After that is merged, the error message will show properly in the frontend.

File: source/faucet/main.d [hunk 1]
```diff
@@ -382,6 +382,14 @@ public class Faucet : FaucetAPI
         auto owned_utxo_rng = this.state.owned_utxos.byKeyValue()
             // do not pick already used UTXOs
             .filter!(pair => pair.key !in this.used_utxos);
+
+        assert(owned_utxo_rng.walkLength >= 0);
```
Comment (ferencdg) [inline source/faucet/main.d:386]: walkLength can be a expensive operation - it is linear and not constant - it walks through the entire list to count the number of elements

can we save down walkLength into a separate variable instead of calling twice?

File: source/faucet/main.d [hunk 2]
```diff
@@ -382,6 +382,14 @@ public class Faucet : FaucetAPI
...
+        if (owned_utxo_rng.walkLength <= 1)
```
Comment (ferencdg) [inline source/faucet/main.d:387]: After this change, we also need to make sure no robots are getting all the UTXOs and starving others from test BOA. Pretty much all Ethereum test faucets have either captcha/facebook post type of authentication.

File: source/faucet/main.d (hunk 1 above)
Comment (kchulj) [reply source/faucet/main.d:386]: Oh I did not know `walkLength` is expensive.
In this case, your suggestion is good.

Comment (kchulj) [reply source/faucet/main.d]: Updated.

File: source/faucet/main.d (hunk 2 above)
Comment (ferencdg) [reply source/faucet/main.d]: If we do end up in a situation where there will be only 1 UTXO, how will we recover? Do we send 'utxo split' transaction in the current block, so in the next block we will have more than 1 UTXOs?

Comment (kchulj) [reply source/faucet/main.d]: If there is only one `UTXO`, the function throws an `Exception` and does not do anything.
So yes, if the faucet detects this number, it will perform a `split` and there will be > 1 `UTXO`s the next block.

File: source/faucet/main.d (hunk 1 above)
Comment (ferencdg) [reply source/faucet/main.d]: > Updated.

you can actually make this better you don't need walkLength at all, cause you need only to know if the length is 0 or 1, so I think you can use the InputRange's empty() and front() functions

File: source/faucet/main.d (hunk 2 above)
Comment (ferencdg) [reply source/faucet/main.d]: you can you popFront() and empty() and avoid using walkLength

Comment (kchulj) [reply source/faucet/main.d]: Do you mean checking if the range is `empty` after a `popFront` call?

Comment (ferencdg) [reply source/faucet/main.d]: you only need to know if the owned_utxo_rng array has a length of
0 or
1 or 
more

if you use popFront and empty multiple times in a certain order then you can get the answers for those questions without using walkLength

File: source/faucet/main.d [hunk 3]
```diff
@@ -382,6 +382,15 @@ public class Faucet : FaucetAPI
...
+
+        auto owned_utxo_len = owned_utxo_rng.walkLength;
+        assert(owned_utxo_len >= 0);
+        if (owned_utxo_len <= 1)
+        {
+            logError("Insufficient UTXOs in storage. # of UTXOs: %s", owned_utxo_len);
+            throw new Exception(format("Insufficient UTXOs in storage. # of UTXOs: %s", owned_utxo_len));
+        }
+
         auto first_utxo = owned_utxo_rng.front;
```
Comment (hewison-chris) [inline source/faucet/main.d:394]: Perhaps consider using `take(1)` and then check the length (take will take up to the given number without assertion or throw). If it is zero then throw.

**Review by hewison-chris — CHANGES_REQUESTED** [review]
Good start.

File: source/faucet/main.d (hunk 3 above)
Comment (kchulj) [reply source/faucet/main.d:394]: Good idea, but I could not check the length of `owned_utxo_rng` without calling `walkLength`. The range does not accept `length` or `size`.

Comment (hewison-chris) [reply source/faucet/main.d:394]: I meant to check the length of the result of take(1).

Comment (hewison-chris) [inline source/faucet/main.d:394]:
```suggestion
        auto first_utxo = owned_utxo_rng.take(1).array;
        if (first_utxo.length == 0)
        {
            logError("Insufficient UTXOs in storage. # of UTXOs: %s", owned_utxo_len);
            throw new Exception(format("Insufficient UTXOs in storage. # of UTXOs: %s", owned_utxo_len));
        } else {
           ....
        }
```

Comment (hewison-chris) [reply source/faucet/main.d:394]: Something like that ^

Comment (kchulj) [reply source/faucet/main.d:394]: Oh, I didn't think of the `array` call..?

Comment (kchulj) [reply source/faucet/main.d:394]: I was trying to avoid the `array` though.

Comment (hewison-chris) [reply source/faucet/main.d:394]: Why? It is only at most 1 in length.

**Comment by kchulj** [comment]
Ping @Geod24 for review / suggestions.
We want to check whether the length of the range is less than or equal to 0. Below are some options we discussed :
1. call `walkLength` on the range
2. call `popFront` and `empty`, possibly with a `count` variable
3. call `array` + `length`

File: source/faucet/main.d (hunk 3 above)
Comment (kchulj) [reply source/faucet/main.d:394]: Yes, or 2 because `length == 1` should also throw.

Comment (hewison-chris) [reply source/faucet/main.d:394]: ok so you create an array with at most two elements.

Comment (hewison-chris) [reply source/faucet/main.d:394]: Also I thought if you use the last UTXO it will have change which will result in another UTXO. So you can use the last one.

Comment (hewison-chris) [reply source/faucet/main.d:394]: :thinking:

Comment (kchulj) [reply source/faucet/main.d:394]: we are apparently `Attempting to fetch the front of an empty filter`.

Comment (hewison-chris) [reply source/faucet/main.d:394]: Push your branch and I'll take a look.

Comment (hewison-chris) [reply source/faucet/main.d:394]: You probably didn't use array `opindex` (i.e. first_utxo[0] ) ?

File: source/faucet/main.d [hunk 4]
```diff
@@ -382,6 +382,15 @@ public class Faucet : FaucetAPI
         auto owned_utxo_rng = this.state.owned_utxos.byKeyValue()
             // do not pick already used UTXOs
             .filter!(pair => pair.key !in this.used_utxos);
+
+        auto owned_utxo_len = owned_utxo_rng.take(2).array.length;
+        assert(owned_utxo_len >= 0);
```
Comment (hewison-chris) [inline source/faucet/main.d:387]: I think this check is not needed.

File: source/faucet/main.d [hunk 5]
```diff
@@ -382,6 +382,15 @@ public class Faucet : FaucetAPI
         auto owned_utxo_rng = this.state.owned_utxos.byKeyValue()
             // do not pick already used UTXOs
             .filter!(pair => pair.key !in this.used_utxos);
+
+        auto owned_utxo_len = owned_utxo_rng.take(2).array.length;
```
Comment (hewison-chris) [inline source/faucet/main.d:386]: You can use count directly and avoid the `array` call as `length` (or is it `count`) is also terminating the lazy range access.

**Review by hewison-chris — CHANGES_REQUESTED** [review]

File: source/faucet/main.d (hunk 5 above)
Comment (kchulj) [reply source/faucet/main.d]: Updated to use `count`.

**Review by hewison-chris — APPROVED** [review]
LGTM

**Review by Geod24 — APPROVED** [review]
