### PR TITLE
Fix calculation of average amount in `send` method

### LINKED ISSUE #129: The `Average` amount in `send()` is broken
It shows 0 because it is not calculated properly.
```
Aug 30 05:30:52 eu-001.bosagora.io docker[244901]: [main(j6eP) INF] Updating state: blocks [5440 .. 5440] (1)
Aug 30 05:30:52 eu-001.bosagora.io docker[244901]: [main(j6eP) INF] UTXO delta: 81
Aug 30 05:30:52 eu-001.bosagora.io docker[244901]: [main(j6eP) INF] About to send transactions...
Aug 30 05:30:52 eu-001.bosagora.io docker[244901]: [main(j6eP) INF]         UTXO set: 179 entries
Aug 30 05:30:52 eu-001.bosagora.io docker[244901]: [main(j6eP) INF]         Median: 48795177417, Avg: 0
Aug 30 05:30:52 eu-001.bosagora.io docker[244901]: [main(j6eP) INF]         L: 10224522, H: 3988242477544347
```

### PR DESCRIPTION
**Pull request by kchulj**
It showed 0 because the calculation was wrong.
Now, the average amount is calculated properly.

```
[main(k/Y/) INF]    UTXO set: 16 entries
[main(k/Y/) INF]    Median: 304999999906200, Avg: 304999999906200
[main(k/Y/) INF]    L: 304999999906200, H: 304999999906200
```

Fixes #129

### CODE REVIEW

**Review by hewison-chris — APPROVED** [review]
LGTM

File: source/faucet/main.d [hunk 1]
```diff
@@ -348,6 +348,7 @@ public class Faucet : FaucetAPI
                     Amount result = a;
                     if (!a.add(b))
                         throw new Exception("Internal error while summing UTXOs");
+                    result.add(b);
                     return result;
```
Comment (Geod24) [inline source/faucet/main.d:352]: Ah, well, this whole hack is not needed anymore.
You can just replace that `fold` call with `sum`, since we added operator overload.

Comment (kchulj) [reply source/faucet/main.d:352]: Tested and works, will update.

Comment (kchulj) [reply source/faucet/main.d:352]: We can remove the `Exception` right?
