### PR TITLE
Display reason in frontend when `postTransaction` fails

### LINKED ISSUE #184: Faucet should check `postTransaction` return value for user BOA requests
before reporting success to the frontend

### PR DESCRIPTION
**Pull request by mkykadir**
Fixes #184

### CODE REVIEW

File: source/faucet/main.d [hunk 1]
```diff
@@ -533,7 +533,9 @@ public class Faucet : FaucetAPI
             .draw(amount, [pubkey])
             .sign(freeze ? OutputType.Freeze : OutputType.Payment);
         log.info("Sending {} BOA to {}", amount, recv);
-        this.randomClient().postTransaction(tx);
+        TransactionResult result = this.randomClient().postTransaction(tx);
+        ensure(result.status == TransactionResult.Status.Accepted,
```
Comment (mkykadir) [inline source/faucet/main.d:537]: Might need to put after following lines (i.e. `increaseMetricBy`); couldn't decide.

**Review by omerfirmak — APPROVED** [review]
